plugins {
    id 'java'
    id 'idea'

    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'io.github.tpalucki'
version = '0.0.1-SNAPSHOT'

java {
}

repositories {
    mavenCentral()
}

// 1. Enable preview for Java compilation tasks
tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += '--enable-preview'
}
// 2. Enable preview for application execution tasks
tasks.withType(JavaExec).configureEach {
    jvmArgs += '--enable-preview'
}
// 3. Enable preview for JUnit / Test tasks
tasks.withType(Test).configureEach {
    useJUnitPlatform()
    jvmArgs += '--enable-preview'
}

dependencies {
    testImplementation("org.assertj:assertj-core:4.0.0-M1")
    testImplementation(platform('org.junit:junit-bom:5.10.2'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')

    testImplementation 'org.mockito:mockito-core:5.11.0'

    implementation('org.springframework.boot:spring-boot-starter-webmvc')
    testImplementation('org.springframework.boot:spring-boot-starter-webmvc-test')
}